In [3]:
print("Hello World")

Hello World


In [2]:
# TensorFlow and tf.keras
import tensorflow as tf
# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

In [5]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [18]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [20]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [22]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.51452005,  0.4433397 , -0.47653946, -0.4527587 ,  0.6064324 ,
         0.08015642,  0.22381873,  0.3449875 , -0.17052495, -0.2904794 ]],
      dtype=float32)

In [24]:
tf.nn.softmax(predictions).numpy()

array([[0.05648155, 0.14719726, 0.05866801, 0.06007989, 0.17327265,
        0.10236966, 0.11818518, 0.13340925, 0.07967127, 0.07066529]],
      dtype=float32)

In [27]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [28]:
loss_fn(y_train[:1], predictions).numpy()

2.2791648

In [30]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [31]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2022-03-25 11:19:04.431624: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 10s 5ms/step - loss: 0.2903 - accuracy: 0.9162
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1352 - accuracy: 0.9592
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1013 - accuracy: 0.9694
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0801 - accuracy: 0.9753
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0671 - accuracy: 0.9781


In [33]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0771 - accuracy: 0.9785 - 879ms/epoch - 3ms/step


[0.07707535475492477, 0.9785000681877136]

In [34]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [35]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.8697952e-08, 8.9549381e-09, 2.4307001e-06, 1.8319188e-04,
        1.8360194e-10, 1.9713097e-07, 3.3815951e-12, 9.9981326e-01,
        4.6469239e-07, 3.8379810e-07],
       [8.2846519e-08, 9.7403637e-05, 9.9985647e-01, 4.0162948e-05,
        2.6746771e-14, 1.4386167e-07, 1.8486327e-08, 1.5726150e-11,
        5.7053257e-06, 1.0765750e-12],
       [2.8586805e-07, 9.9590379e-01, 2.5092792e-03, 8.9863834e-06,
        1.0231576e-05, 3.8634025e-06, 8.7420376e-05, 1.1326839e-03,
        3.4337136e-04, 9.9175999e-08],
       [9.9996519e-01, 3.9628539e-10, 2.0811822e-05, 4.2508717e-07,
        6.8427582e-08, 1.5022545e-06, 1.5850554e-06, 9.6954327e-06,
        1.2918359e-09, 6.1458621e-07],
       [2.2733734e-06, 1.4344197e-09, 3.6031856e-06, 3.2267161e-07,
        9.9889594e-01, 1.3804483e-07, 7.4230536e-07, 3.3524626e-05,
        5.6349364e-08, 1.0634237e-03]], dtype=float32)>